# This is an example of variable definition for
# inventory host group do_grp1. As the yml file 
# suggests, the hosts file must contain the group "[do_grp1]"
# definition with a list of IPs or hostname under that group.
# All variables definition in here pertains to the group, unless
# it is overrided elsewhere.

fbsd_nginx_ssl_path: /www/ssl

fbsd_php_list:
  - [php71]
  - [php71-curl]
  - [php71-exif]
  - [php71-fileinfo]
  - [php71-gd]
  - [php71-gettext]
  - [php71-hash]
  - [php71-iconv]
  - [php71-intl]
  - [php71-json]
  - [php71-ldap]
  - [php71-mbstring]
  - [php71-mcrypt]
  - [php71-mysqli]
  - [php71-pdo]
  - [php71-pgsql]
  - [php71-pspell]
  - [php71-session]
  - [php71-simplexml]
  - [php71-soap]
  - [php71-socket]
  - [php71-tokenizer]
  - [php71-xml]
  - [php71-xmlrpc]
