# TODO:  
#   - common task for FreeBSD like pkg updat/upgrade

---
# tasks file for {{ role_name }}
- name: Ensure package is up-to-date
  pkgng:
      name: pkg
      cached: no
      autoremove: yes
      state: present

# setup local timezone
- name: Ensure timezone is "{{ fbsd_timezone }}"
  copy:
      src: "{{ fbsd_timezone_src }}/{{fbsd_timezone}}"
      dest: "{{ fbsd_timezone_dest }}"
      owner: root
      group: wheel

# install common utilities
# the variable freebsd_common_utils is defined in
# roles/common/vars/main.yml -- this is the main
# file to define role variables if you wish to add more
- name: Ensure essential system utiltities
  pkgng:
     name: "{{ item.name }}"
     state: present
  with_tems:
      - "{{ fbsd_common_utils }}"

- name: Sysctl ensure optimal value
  sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_set: "{{ item.apply }}"
  with_items:
      - "{{ fbsd_sysctl_opt }}"

###############################################################
# Security
###############################################################
# TODO:  change ttyv0 and dcons in /etc/ttys from secure to insecure
#        perhaps this can be done w/perl -pi -e ... 

- name: Ensure systctl secruity settings 
  sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      sysctl_set: yes
  with_items:
      - "{{ fbsd_sysctl_security }}"
