# variables set in one role are available to others
# so the variables defined here can be used in other roles
#

---
fbsd_common_utils:
  - {name: vim}
  - {name: htop}
  - {name: iftop}
  - {name: git}

############################################################### 
# http://docs.ansible.com/ansible/latest/sysctl_module.html
# tune some system variables 
############################################################
fbsd_sysctl_opt:
  - {name: kern.ipc.soacceptqueue,            value: 1024,               apply: 'yes'}
  - {name: kern.maxvnodes,                    value: 75000,              apply: 'yes'}
  - {name: kern.randompid,                    value: '$(jot -r 1 9999)', apply: 'no'}
  - {name: net.inet.ip.forwarding,            value: 1,                  apply: 'yes'}
    #  - {name: net.inet.tcp.cc.algorithm,         value: 'htcp',             apply: 'yes'}
  - {name: net.inet.tcp.cc.htcp.rtt_scaling,  value: 1,                  apply: 'yes'}

############################################################### 
# other network tuning -- use with careful consideration, if you don't
# know what it is for, don't set it and read more about it.
# ref: https://calomel.org/freebsd_network_tuning.html
#- name: Enable IP forwarding
############################################################### 
fbsd_sysctl_security:
  - {key: security.bsd.unprivileged_read_msgbuf, value: 0,    name: 'Disable unprivileged user read to message buffer'}
  - {key: security.bsd.unprivileged_proc_debug,  value: 0,    name: 'Disable unprivileged user process'}
  - {key: security.bsd.see_other_uids,           value: 0,    name: 'Disable user to see other uids'}
  - {key: security.bsd.see_other_gids,           value: 0,    name: 'Disable user to see other gids'}
  - {key: security.bsd.stack_guard_page,         value: 1,    name: 'Secure stack guard page'}
  - {key: net.inet.udp.blackhole,                value: 1,    name: 'Drop UCDP destined for closed sockets'}
  - {key: net.inet.itcp.blackhole,               value: 2,    name: 'Drop TCP destined for closed sockets'}
  - {key: net.inet.ip.intr_queue_maxlen,         value: 2048, name: 'Increase IPv4 outgoing network queue size'}
  - {key: net.route.netisr_maxqlen,              value: 2048, name: 'Increase IPv4 incoming network queue size'}
